### ISSUE TITLE
Hello, I'm new to OpenFeature. Ask, if I need to use GoFeatureFlag as a Provider, is this Operator applicable and how to disable FlagdProxy?

### ISSUE THREAD

**Issue by oomgomgxx** [open-feature/open-feature-operator#591]

**Comment by agardnerIT** [comment]
Tagging the Go Feature Flag maintainer @thomaspoignant here but my understand is:

No, this operator uses [flagd ](https://flagd.dev) as the "backend" and [flags defined in flagd format](https://flagd.dev/reference/flag-definitions/#flag-properties)

That said, I know there are some discussions in the community about further commonality / standardisation so perhaps those discussion move this operator closer to being compatible with Go Feature Flag in the future? I would recommend getting involved in the discussion on Slack (#openfeature channel of [the CNCF slack](https://communityinviter.com/apps/cloud-native/cncf))

**Comment by thomaspoignant** [comment]
Hello @oomgomgxx, as @agardnerIT said for now it is hard to use the operator with something else than flagd.
If you want to use GO Feature Flag with an OpenFeature provider you don't need the open-feature-operator, you can use it directly with the GO Feature Flag relay proxy.

You have some examples in the repo ([here the nodeJS example](https://github.com/thomaspoignant/go-feature-flag/tree/main/examples/openfeature_nodejs)).

That being said, if you are interested in using the `open-feature-operator` along with **GO Feature Flag** it is not possible for now due to some limitations on the operator _(and also lack of time to look at it 😞 )_.

There is an issue open in the GO Feature Flag repo for this https://github.com/thomaspoignant/go-feature-flag/issues/705 you can follow it to see the progress on it, but this is not the top priority right now.
